version: '2'
services:
  php:
    build: ./docker/php
    volumes:
      - ./.:/var/www/simple-api
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    depends_on:
      - mysql
      - mongo
      - redis

  web:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./.:/var/www/simple-api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    expose:
      - 3306

  redis:
    image: redis
    expose:
      - 6379

  mongo:
    image: mongo
    expose:
      - 27017

